"""Per-company Excel data export.

Two independent pieces:
- build_company_workbook: a pure read, rebuilt fresh from the live database
  on every call. Deliberately NOT a stored/incrementally-updated file — this
  codebase has dozens of independent write paths (guided WhatsApp workflows,
  admin CRUD, CSV import, onboarding); hooking every one of them to also
  patch a persisted .xlsx would be exactly the kind of easy-to-miss-a-spot
  design that causes silent staleness. A full rebuild can never be "half
  updated." Uses openpyxl's write_only streaming writer (already a project
  dependency) plus server-side streamed reads for the large tables, so
  memory stays bounded regardless of how many rows a company accumulates.
- generate_export_link: a short-lived HMAC-signed URL for the WhatsApp-facing
  download path, verified statelessly by app/api/export.py — nothing is
  written to the database to "issue" a link, so there's nothing to store or
  revoke. Same signing pattern this codebase already uses to verify Meta's
  own webhook payloads (app/api/webhooks/whatsapp.py's X-Hub-Signature-256).
"""

from __future__ import annotations

import hashlib
import hmac
import io
import time
import uuid
from datetime import UTC, datetime

from openpyxl import Workbook
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import get_settings
from app.models.business_event import BusinessEvent
from app.models.company import Company
from app.models.daily_business_snapshot import DailyBusinessSnapshot
from app.models.dealer import Dealer
from app.models.faq import FAQ
from app.models.invoice import Invoice, InvoiceDirection, InvoiceStatus
from app.models.payment import Payment
from app.models.product import Product
from app.models.supplier import Supplier
from app.services.party_outstanding import calculate_outstanding_for_company

EXPORT_FORMAT_VERSION = "1.0"

_OPEN_STATUSES = (InvoiceStatus.Pending, InvoiceStatus.Partially_Paid, InvoiceStatus.Overdue)
_STREAM_CHUNK = 500


def _s(value: object) -> str | None:
    """Render an enum/UUID/None as a plain string cell value."""
    if value is None:
        return None
    return str(value)


async def _write_company_sheet(wb: Workbook, company: Company) -> None:
    ws = wb.create_sheet("Company")
    ws.append(["Generated At", datetime.now(UTC).isoformat()])
    ws.append(["Company", company.business_name])
    ws.append(["Generated By", "OpsGenie"])
    ws.append(["Format Version", EXPORT_FORMAT_VERSION])
    ws.append([])
    ws.append(["Field", "Value"])
    for label, value in [
        ("Business Name", company.business_name),
        ("Owner Name", company.owner_name),
        ("WhatsApp Number", company.whatsapp_number),
        ("Business Type", company.business_type),
        ("GST Number", company.gst_number),
        ("GST Rate (%)", company.gst_rate),
        ("Timezone", company.timezone),
        ("Subscription Active", company.subscription_active),
        ("Opening Balance", company.opening_balance),
        ("Briefing Hour", company.briefing_hour),
        ("Evening Brief Hour", company.evening_brief_hour),
        ("Activated/Created At", company.created_at.isoformat() if company.created_at else None),
    ]:
        ws.append([label, value])


async def _write_products_sheet(db: AsyncSession, wb: Workbook, company_id: uuid.UUID) -> None:
    ws = wb.create_sheet("Products")
    ws.append(["Name", "Unit", "Selling Price", "Purchase Price", "Stock Quantity"])
    products = await db.scalars(
        select(Product).where(Product.company_id == company_id).order_by(Product.name)
    )
    for p in products:
        ws.append([p.name, p.unit, p.selling_price, p.purchase_price, p.stock_quantity])


async def _write_party_sheet(
    db: AsyncSession,
    wb: Workbook,
    company_id: uuid.UUID,
    *,
    model: type[Dealer] | type[Supplier],
    sheet_name: str,
    direction: str,
) -> None:
    ws = wb.create_sheet(sheet_name)
    ws.append(
        [
            "Name",
            "Phone",
            "Address",
            "GST Number",
            "Payment Terms (days)",
            "Credit Limit",
            "Notes",
            "Outstanding",
        ]
    )
    parties = (
        (await db.scalars(select(model).where(model.company_id == company_id).order_by(model.name)))
        .all()
    )
    outstanding_by_party = await calculate_outstanding_for_company(
        db, company_id=company_id, direction=direction
    )
    for party in parties:
        # Dealer has address/gst_number; Supplier doesn't — getattr keeps one
        # shared column layout for both sheets instead of two divergent ones.
        ws.append(
            [
                party.name,
                party.phone,
                getattr(party, "address", None),
                getattr(party, "gst_number", None),
                party.payment_terms_days,
                party.credit_limit,
                party.notes,
                outstanding_by_party.get(party.id, 0),
            ]
        )


async def _write_open_invoices_sheet(
    db: AsyncSession,
    wb: Workbook,
    company_id: uuid.UUID,
    *,
    sheet_name: str,
    direction: InvoiceDirection,
) -> None:
    ws = wb.create_sheet(sheet_name)
    ws.append(["Counterparty", "Invoice Number", "Due Date", "Days Overdue", "Amount Outstanding"])
    today = datetime.now(UTC).date()

    invoices = (
        (
            await db.scalars(
                select(Invoice)
                .where(
                    Invoice.company_id == company_id,
                    Invoice.direction == direction,
                    Invoice.status.in_(_OPEN_STATUSES),
                )
                .order_by(Invoice.due_date)
            )
        )
        .all()
    )
    if not invoices:
        return
    invoice_ids = [inv.id for inv in invoices]
    paid_rows = await db.execute(
        select(Payment.invoice_id, func.sum(Payment.amount))
        .where(Payment.invoice_id.in_(invoice_ids))
        .group_by(Payment.invoice_id)
    )
    paid_by_invoice: dict[uuid.UUID, object] = dict(paid_rows.all())

    party_ids = {inv.dealer_id if direction == InvoiceDirection.receivable else inv.supplier_id
                 for inv in invoices}
    party_ids.discard(None)
    model = Dealer if direction == InvoiceDirection.receivable else Supplier
    names = {
        p.id: p.name
        for p in (await db.scalars(select(model).where(model.id.in_(party_ids)))).all()
    }

    for inv in invoices:
        party_id = inv.dealer_id if direction == InvoiceDirection.receivable else inv.supplier_id
        paid = paid_by_invoice.get(inv.id, 0)
        outstanding = inv.total_amount - paid
        days_overdue = max((today - inv.due_date).days, 0)
        ws.append(
            [
                names.get(party_id, "Unknown"),
                inv.invoice_number,
                inv.due_date,
                days_overdue,
                outstanding,
            ]
        )


async def _write_invoices_sheet(db: AsyncSession, wb: Workbook, company_id: uuid.UUID) -> None:
    ws = wb.create_sheet("Invoices")
    ws.append(
        [
            "Invoice Number",
            "Direction",
            "Counterparty",
            "Invoice Date",
            "Due Date",
            "Subtotal",
            "GST Amount",
            "Total Amount",
            "Status",
            "Source",
            "Amount Paid",
            "Amount Outstanding",
        ]
    )
    dealers = {
        d.id: d.name
        for d in (await db.scalars(select(Dealer).where(Dealer.company_id == company_id))).all()
    }
    suppliers = {
        s.id: s.name
        for s in (await db.scalars(select(Supplier).where(Supplier.company_id == company_id))).all()
    }
    # One grouped query for every invoice's paid total — not one SUM query per
    # invoice, which would defeat the point of streaming the invoices below.
    paid_rows = await db.execute(
        select(Payment.invoice_id, func.sum(Payment.amount))
        .join(Invoice, Payment.invoice_id == Invoice.id)
        .where(Invoice.company_id == company_id)
        .group_by(Payment.invoice_id)
    )
    paid_by_invoice: dict[uuid.UUID, object] = dict(paid_rows.all())

    stmt = (
        select(Invoice)
        .where(Invoice.company_id == company_id)
        .order_by(Invoice.invoice_date)
        .execution_options(yield_per=_STREAM_CHUNK)
    )
    result = await db.stream_scalars(stmt)
    async for invoice in result:
        paid_total = paid_by_invoice.get(invoice.id, 0)
        counterparty = (
            dealers.get(invoice.dealer_id)
            if invoice.direction == InvoiceDirection.receivable
            else suppliers.get(invoice.supplier_id)
        )
        ws.append(
            [
                invoice.invoice_number,
                _s(invoice.direction),
                counterparty or "Unknown",
                invoice.invoice_date,
                invoice.due_date,
                invoice.subtotal,
                invoice.gst_amount,
                invoice.total_amount,
                _s(invoice.status),
                _s(invoice.source),
                paid_total,
                invoice.total_amount - paid_total,
            ]
        )


async def _write_payments_sheet(db: AsyncSession, wb: Workbook, company_id: uuid.UUID) -> None:
    ws = wb.create_sheet("Payments")
    ws.append(["Amount", "Payment Date", "Method", "Source", "Invoice Number", "Direction"])
    invoice_lookup = {
        inv.id: (inv.invoice_number, inv.direction)
        for inv in (
            await db.scalars(select(Invoice).where(Invoice.company_id == company_id))
        ).all()
    }
    stmt = (
        select(Payment)
        .where(Payment.company_id == company_id)
        .order_by(Payment.payment_date)
        .execution_options(yield_per=_STREAM_CHUNK)
    )
    result = await db.stream_scalars(stmt)
    async for payment in result:
        invoice_number, direction = invoice_lookup.get(payment.invoice_id, (None, None))
        ws.append(
            [
                payment.amount,
                payment.payment_date,
                payment.method,
                _s(payment.source),
                invoice_number,
                _s(direction),
            ]
        )


async def _write_daily_summary_sheet(db: AsyncSession, wb: Workbook, company_id: uuid.UUID) -> None:
    ws = wb.create_sheet("Daily Business Summary")
    ws.append(
        [
            "Date",
            "Sales",
            "Sales Margin",
            "Collections",
            "Supplier Payments",
            "Net Cash Movement",
            "Outstanding Receivables",
            "Invoices Created",
            "Payments Recorded",
            "Orders via WhatsApp",
        ]
    )
    rows = await db.scalars(
        select(DailyBusinessSnapshot)
        .where(DailyBusinessSnapshot.company_id == company_id)
        .order_by(DailyBusinessSnapshot.business_date)
    )
    for r in rows:
        ws.append(
            [
                r.business_date,
                r.sales_amount,
                r.sales_margin,
                r.collections_amount,
                r.supplier_payments_amount,
                r.net_cash_movement,
                r.outstanding_receivables,
                r.invoices_created,
                r.payments_recorded,
                r.orders_created,
            ]
        )


async def _write_activity_log_sheet(db: AsyncSession, wb: Workbook, company_id: uuid.UUID) -> None:
    ws = wb.create_sheet("Activity Log")
    ws.append(["Timestamp", "Event Type", "Entity Type", "Details"])
    stmt = (
        select(BusinessEvent)
        .where(BusinessEvent.company_id == company_id)
        .order_by(BusinessEvent.created_at)
        .execution_options(yield_per=_STREAM_CHUNK)
    )
    result = await db.stream_scalars(stmt)
    async for event in result:
        ws.append(
            [
                event.created_at.isoformat() if event.created_at else None,
                _s(event.event_type),
                event.entity_type,
                str(event.payload) if event.payload else None,
            ]
        )


async def _write_faqs_sheet(db: AsyncSession, wb: Workbook, company_id: uuid.UUID) -> None:
    ws = wb.create_sheet("FAQs")
    ws.append(["Question", "Answer"])
    faqs = await db.scalars(
        select(FAQ).where(FAQ.company_id == company_id).order_by(FAQ.created_at)
    )
    for faq in faqs:
        ws.append([faq.question, faq.answer])


async def build_company_workbook(db: AsyncSession, company: Company) -> bytes:
    """Rebuild the entire per-company workbook fresh from the live database.
    Pure read — never commits, never mutates. A freshly-activated company with
    no data yet naturally produces headers-only sheets.
    """
    wb = Workbook(write_only=True)
    await _write_company_sheet(wb, company)
    await _write_products_sheet(db, wb, company.id)
    await _write_party_sheet(
        db, wb, company.id, model=Dealer, sheet_name="Dealers", direction="receivable"
    )
    await _write_party_sheet(
        db, wb, company.id, model=Supplier, sheet_name="Suppliers", direction="payable"
    )
    await _write_open_invoices_sheet(
        db, wb, company.id, sheet_name="Receivables", direction=InvoiceDirection.receivable
    )
    await _write_open_invoices_sheet(
        db, wb, company.id, sheet_name="Payables", direction=InvoiceDirection.payable
    )
    await _write_invoices_sheet(db, wb, company.id)
    await _write_payments_sheet(db, wb, company.id)
    await _write_daily_summary_sheet(db, wb, company.id)
    await _write_activity_log_sheet(db, wb, company.id)
    await _write_faqs_sheet(db, wb, company.id)

    buffer = io.BytesIO()
    wb.save(buffer)
    return buffer.getvalue()


def generate_export_link(company: Company, *, base_url: str) -> str:
    """Stateless short-lived signed link — nothing is written to the database
    to "issue" it, so there's nothing to store or revoke. Same HMAC signing
    convention already used to verify Meta's webhook payloads.
    """
    settings = get_settings()
    if not settings.export_link_secret:
        raise ValueError("EXPORT_LINK_SECRET is not configured.")
    expires_at = int(time.time()) + settings.export_link_ttl_minutes * 60
    message = f"{company.id}:{expires_at}"
    signature = hmac.new(
        settings.export_link_secret.encode(), message.encode(), hashlib.sha256
    ).hexdigest()
    return f"{base_url.rstrip('/')}/export/{company.id}/{expires_at}/{signature}"


def verify_export_link(company_id: uuid.UUID, expires_at: int, signature: str) -> bool:
    settings = get_settings()
    if not settings.export_link_secret:
        return False
    if time.time() > expires_at:
        return False
    message = f"{company_id}:{expires_at}"
    expected = hmac.new(
        settings.export_link_secret.encode(), message.encode(), hashlib.sha256
    ).hexdigest()
    return hmac.compare_digest(expected, signature)
