"""add_invoice_number_unique

Revision ID: 121a819d90a5
Revises: a09d0163b1e8
Create Date: 2026-07-01 19:29:11.636352

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "121a819d90a5"
down_revision: str | None = "a09d0163b1e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_invoices_company_invoice_number", "invoices", ["company_id", "invoice_number"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_invoices_company_invoice_number", "invoices", type_="unique")
    # ### end Alembic commands ###
