"""add_created_at_to_morning_briefings

Revision ID: 73b309549d77
Revises: 121a819d90a5
Create Date: 2026-07-03 23:20:15.272252

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "73b309549d77"
down_revision: str | None = "121a819d90a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "morning_briefings",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("morning_briefings", "created_at")
    # ### end Alembic commands ###
