"""add_company_timezone

Revision ID: 783d8c755929
Revises: 73b309549d77
Create Date: 2026-07-04 03:03:52.077762

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "783d8c755929"
down_revision: str | None = "73b309549d77"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies",
        sa.Column(
            "timezone", sa.String(), server_default=sa.text("'Asia/Kolkata'"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("companies", "timezone")
    # ### end Alembic commands ###
