"""initial_schema

Revision ID: a09d0163b1e8
Revises: 
Create Date: 2026-07-01 19:16:53.256795

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a09d0163b1e8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=False),
    sa.Column('whatsapp_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('business_type', sa.String(), nullable=True),
    sa.Column('preferred_language', sa.String(), nullable=False),
    sa.Column('subscription_active', sa.Boolean(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp_number', name='uq_companies_whatsapp_number')
    )
    op.create_table('activity_timelines',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('dealer', 'supplier', name='activityentitytype', create_constraint=True), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('invoice_created', 'payment_received', 'reminder_sent', 'dealer_called', 'briefing_mentioned', 'overdue_flagged', 'follow_up_sent', 'follow_up_responded', name='activityeventtype', create_constraint=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_timelines_company_entity', 'activity_timelines', ['company_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index('ix_activity_timelines_company_timestamp', 'activity_timelines', ['company_id', 'event_timestamp'], unique=False)
    op.create_table('business_events',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('invoice_created', 'invoice_status_updated', 'payment_received', 'supplier_paid', 'reminder_sent', 'dealer_called', 'briefing_sent', 'data_imported', 'follow_up_sent', 'follow_up_responded', name='businesseventtype', create_constraint=True), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_business_events_company_created', 'business_events', ['company_id', 'created_at'], unique=False)
    op.create_index('ix_business_events_company_type', 'business_events', ['company_id', 'event_type'], unique=False)
    op.create_table('cash_snapshots',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recorded_by', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dealers',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('gst_number', sa.String(), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dealers_company_id', 'dealers', ['company_id'], unique=False)
    op.create_table('import_logs',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('source_format', sa.String(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rows_processed', sa.Integer(), nullable=False),
    sa.Column('rows_succeeded', sa.Integer(), nullable=False),
    sa.Column('rows_failed', sa.Integer(), nullable=False),
    sa.Column('error_detail_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('morning_briefings',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('generated_text', sa.Text(), nullable=False),
    sa.Column('snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('data_freshness_hours', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_status', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_morning_briefings_company_sent', 'morning_briefings', ['company_id', 'sent_at'], unique=False)
    op.create_table('notification_logs',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('recipient_whatsapp', sa.String(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivery_status', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_company_id', 'products', ['company_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_suppliers_company_id', 'suppliers', ['company_id'], unique=False)
    op.create_table('invoices',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('direction', sa.Enum('receivable', 'payable', name='invoicedirection', create_constraint=True), nullable=False),
    sa.Column('dealer_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('Draft', 'Sent', 'Pending', 'Partially_Paid', 'Paid', 'Overdue', 'Cancelled', name='invoicestatus', create_constraint=True), nullable=False),
    sa.Column('source', sa.Enum('csv_import', 'whatsapp', name='invoicesource', create_constraint=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('dealer_id IS NOT NULL OR supplier_id IS NOT NULL', name='ck_invoices_dealer_or_supplier'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoices_company_due_date', 'invoices', ['company_id', 'due_date'], unique=False)
    op.create_index('ix_invoices_company_id', 'invoices', ['company_id'], unique=False)
    op.create_index('ix_invoices_company_status', 'invoices', ['company_id', 'status'], unique=False)
    op.create_table('invoice_items',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('csv_import', 'whatsapp', name='paymentsource', create_constraint=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_company_id', 'payments', ['company_id'], unique=False)
    op.create_index('ix_payments_invoice_id', 'payments', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_invoice_id', table_name='payments')
    op.drop_index('ix_payments_company_id', table_name='payments')
    op.drop_table('payments')
    op.drop_table('invoice_items')
    op.drop_index('ix_invoices_company_status', table_name='invoices')
    op.drop_index('ix_invoices_company_id', table_name='invoices')
    op.drop_index('ix_invoices_company_due_date', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_suppliers_company_id', table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index('ix_products_company_id', table_name='products')
    op.drop_table('products')
    op.drop_table('notification_logs')
    op.drop_index('ix_morning_briefings_company_sent', table_name='morning_briefings')
    op.drop_table('morning_briefings')
    op.drop_table('import_logs')
    op.drop_index('ix_dealers_company_id', table_name='dealers')
    op.drop_table('dealers')
    op.drop_table('cash_snapshots')
    op.drop_index('ix_business_events_company_type', table_name='business_events')
    op.drop_index('ix_business_events_company_created', table_name='business_events')
    op.drop_table('business_events')
    op.drop_index('ix_activity_timelines_company_timestamp', table_name='activity_timelines')
    op.drop_index('ix_activity_timelines_company_entity', table_name='activity_timelines')
    op.drop_table('activity_timelines')
    op.drop_table('companies')
    # Drop PostgreSQL native enum types — autogenerate does not emit these.
    sa.Enum(name='paymentsource').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='invoicesource').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='invoicestatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='invoicedirection').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='businesseventtype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='activityeventtype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='activityentitytype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

